import AppKit
import Foundation
import CryptoKit

@objc(ClipboardMonitor)
class ClipboardMonitor: RCTEventEmitter {

  private var timer: Timer?
  private var lastChangeCount: Int = -1
  private let pollInterval: TimeInterval = 0.4

  override func supportedEvents() -> [String]! {
    return ["onClipboardChange"]
  }

  @objc override static func requiresMainQueueSetup() -> Bool {
    return false
  }

  private var imageDirectory: String {
    let fm = FileManager.default
    if let support = fm.urls(for: .applicationSupportDirectory, in: .userDomainMask).first {
      let dir = support.appendingPathComponent("Pastey/images", isDirectory: true)
      return dir.path.hasSuffix("/") ? dir.path : dir.path + "/"
    }
    return NSTemporaryDirectory() + "pastey/"
  }

  /// Deletes every file in the image directory that is not in `keepPaths`.
  @objc func syncImages(
    _ keepPaths: [String],
    resolver resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    let dir = imageDirectory
    let keep = Set(keepPaths)

    guard let entries = try? FileManager.default.contentsOfDirectory(atPath: dir) else {
      resolve(0)
      return
    }

    var removed = 0
    for entry in entries {
      let path = dir + entry
      if keep.contains(path) {
        continue
      }
      if (try? FileManager.default.removeItem(atPath: path)) != nil {
        removed += 1
      }
    }

    resolve(removed)
  }

  @objc func start() {
    DispatchQueue.main.async { [weak self] in
      guard let self = self else { return }
      self.lastChangeCount = NSPasteboard.general.changeCount
      self.timer?.invalidate()
      self.timer = Timer.scheduledTimer(
        withTimeInterval: self.pollInterval,
        repeats: true
      ) { [weak self] _ in
        self?.poll()
      }
    }
  }

  @objc func stop() {
    DispatchQueue.main.async { [weak self] in
      self?.timer?.invalidate()
      self?.timer = nil
    }
  }

  private func sha256(_ str: String) -> String {
    let digest = SHA256.hash(data: Data(str.utf8))
    return digest.map { String(format: "%02x", $0) }.joined()
  }

  private func poll() {
    let pb = NSPasteboard.general
    guard pb.changeCount != lastChangeCount else { return }
    lastChangeCount = pb.changeCount
    guard let payload = readPasteboard(pb) else { return }
    sendEvent(withName: "onClipboardChange", body: payload)
  }

  @objc func write(
    _ type: String,
    content: String,
    filePath: String,
    resolver resolve: @escaping RCTPromiseResolveBlock,
    rejecter reject: @escaping RCTPromiseRejectBlock
  ) {
    DispatchQueue.main.async { [weak self] in
      guard let self = self else { return }

      let pb = NSPasteboard.general
      pb.clearContents()

      if type == "image", !filePath.isEmpty,
        let data = try? Data(contentsOf: URL(fileURLWithPath: filePath)) {
        let ext = (filePath as NSString).pathExtension.lowercased()
        let pbType = pasteboardType(forExtension: ext) ?? .png
        pb.setData(data, forType: pbType)
      } else if !content.isEmpty {
        pb.setString(content, forType: .string)
      } else {
        reject("empty", "Nothing to write", nil)
        return
      }

      // Suppress the echo: our own write bumps changeCount,
      // and we don't want that to re-insert the item.
      self.lastChangeCount = pb.changeCount

      resolve(true)
    }
  }

  private func readPasteboard(_ pb: NSPasteboard) -> [String: Any]? {
    let types = pb.types?.map { $0.rawValue } ?? []
    if types.contains("org.nspasteboard.ConcealedType") ||
       types.contains("org.nspasteboard.TransientType") ||
       types.contains("org.nspasteboard.AutoGeneratedType") {
      return nil
    }

    let bundleId = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? ""
    let now = Date().timeIntervalSince1970 * 1000

    if let str = pb.string(forType: .string), !str.isEmpty {
      return [
        "hash": sha256(str),
        "type": "text",
        "preview": String(str.prefix(200)),
        "content": str,
        "bundleId": bundleId,
        "createdAt": now,
      ]
    }

    if let rep = bestImageRep(pb) {
      let captureImages = UserDefaults.standard.object(forKey: "captureImages") as? Bool ?? true
      guard captureImages else { return nil }

      let maxMb = UserDefaults.standard.object(forKey: "maxImageMb") as? Double ?? 10.0
      if Double(rep.data.count) > maxMb * 1024 * 1024 {
        return nil
      }

      let dir = imageDirectory
      try? FileManager.default.createDirectory(
        atPath: dir,
        withIntermediateDirectories: true
      )
      let path = dir + "\(UUID().uuidString).\(rep.ext)"
      do {
        try rep.data.write(to: URL(fileURLWithPath: path))
        return [
          "hash": sha256(rep.data.base64EncodedString()),
          "type": "image",
          "preview": "[image]",
          "content": "",
          "filePath": path,
          "bundleId": bundleId,
          "createdAt": now,
        ]
      } catch {
        return nil
      }
    }

    return nil
  }

  private func bestImageRep(
    _ pb: NSPasteboard
  ) -> (data: Data, ext: String, uti: String)? {
    let candidates: [(NSPasteboard.PasteboardType, String, String)] = [
      (.init("public.jpeg"), "jpg", "public.jpeg"),
      (.init("public.png"),  "png", "public.png"),
      (.init("public.heic"), "heic", "public.heic"),
      (.init("com.compuserve.gif"), "gif", "com.compuserve.gif"),
      (.init("org.webmproject.webp"), "webp", "org.webmproject.webp"),
      (.init("public.tiff"), "tiff", "public.tiff"),
    ]
    for (pbType, ext, uti) in candidates {
      if let data = pb.data(forType: pbType) {
        return (data, ext, uti)
      }
    }
    return nil
  }

  private func pasteboardType(
    forExtension ext: String
  ) -> NSPasteboard.PasteboardType? {
    switch ext {
    case "jpg", "jpeg": return .init("public.jpeg")
    case "png":         return .init("public.png")
    case "heic":        return .init("public.heic")
    case "gif":         return .init("com.compuserve.gif")
    case "webp":        return .init("org.webmproject.webp")
    case "tiff", "tif": return .init("public.tiff")
    default:            return nil
    }
  }
}
